# Site settings
title: "Jeongeun Park"
description: "A resume template for Jekyll and GitHub Pages sites."

url: "https://agent47ag925.github.io"
baseurl: ""

# --- Add: Asset paths used in head.html ---
main_css: "/main.af46ece4.css"   # 실제 파일명에 맞춰 변경
main_js:  "/main.af46ece4.js"    # 없으면 제거
override_css_version: 2

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jeongeun Park"
resume_title:                   "AI Application Developer For HCI"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jeongeunswd@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+82 10-3649-4926"
resume_contact_address:         "Seoul, South Korea"

resume_header_contact_info:     "Seoul, South Korea • +82 10-3649-4926 • jeongeunswd@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am an AI/ML engineer and computer vision specialist with experience spanning applied research, product development, and professional education. My work focuses on bridging the gap between academic research and real-world applications, delivering both technical innovation and practical impact. With a strong foundation in deep learning, on-device AI, and human-computer interaction, I have led and contributed to projects that integrate advanced models into usable products. In parallel, I have taught AI and computer vision to university students and professionals, highlighting my ability to translate complex concepts into accessible knowledge. My immediate career goal is to expand my research expertise through doctoral studies abroad, while continuing to develop as an independent expert who connects technology, education, and real-world deployment.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/agent47ag925"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/jeongeun-park-5009581ba/"
  resume_instagram_url:         "https://www.instagram.com/jeongeun_47ag925?igsh=MTE3dHY5NWk5bGJ6bA%3D%3D&utm_source=qr"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
